### ISSUE TITLE
Training model failed. class not found: val

### ISSUE THREAD

**Issue by nandexsp** [DmitryUlyanov/texture_nets#20]
I have this directory structure: 
DmitryCode
 ---   train
 ---   val
 ---   texture_nets

And when I launch:   "th train.lua -data ../ -style_image style.jpg"
I get this error :(
" 
=> Generating list of images
 | finding all validation images
find: ‘standard output’: Tubería rota
find: write error
/home/pixie/pixify/torch/install/bin/luajit: /home/pixie/pixify/trainlua/datasets/style-gen.lua:67: class not found: val
stack traceback:
        [C]: in function 'assert'
        /home/pixie/pixify/trainlua/datasets/style-gen.lua:67: in function 'findImages'
        /home/pixie/pixify/trainlua/datasets/style-gen.lua:102: in function 'exec'
        ./datasets/init.lua:28: in function 'create'
        ./dataloader.lua:24: in function 'create'
        train.lua:79: in main chunk
        [C]: in function 'dofile'
        ...xify/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064d0
"

Somebody knows how could I fix this? Thanks

**Comment by ttoinou** [comment]
I had the same error without the dummy folders and now with them I don't have this error and training works..

**Comment by nandexsp** [comment]
what are the dummy folders??

**Comment by DmitryUlyanov** [comment]
Read the description please

**Comment by jamiis** [comment]
Your folder structure needs to mimick fb.resnet.torch because Dmitry used some code from that repo for ingesting training data. This means `-data <dataset>` needs to point to a folder that contains both a `train` directory and a `val` directory, and each of those need to have a directory called `dummy`. This is because fb.resnet.torch is doing supervised learning on image classes where the directory of class "dummy" contains all the photos. Just put all photos in `train/dummy` and make `val/dummy` empty. 

From the README: "The image dataset should be structured as in fb.resnet.torch having train and val folders and some folders corresponding to classes as you were doing classification. You can create a dummy folder train/dymmy/ and val/dummy/ and store all the images in them. Only images from train forlder will be used."

**Comment by nandexsp** [comment]
Thanks :)
