### ISSUE TITLE
-init image option?

### ISSUE THREAD

**Issue by wulabs** [DmitryUlyanov/texture_nets#71]
Instead of initializing with random, is there a way to initialize with the content image? It seems from jcjohnson/neural-style many people have gotten better results with this.

**Comment by DmitryUlyanov** [comment]
Hello, this algorithm is different to neural-style, it does not use optimization process to gradually update an image, but learns a feed forward neural network to stylize a given image. So you can think this method uses content image as initialization since it is an input to the stylization network.
